### ISSUE TITLE
client example doesn't compile w/ latest rand

### ISSUE THREAD

**Issue by jgarvin** [ninjasource/embedded-websocket#5]
rand 0.7.3 works fine, but rand 0.8.3 does not.

```
37  |     let mut ws_client = ws::WebSocketClient::new_client(rand::thread_rng());
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `rand_core::RngCore` is not implemented for `ThreadRng`
```

**Comment by ninjasource** [comment]
I guess the solution would be to bump the rand_core version to 0.6. Not the first time this has happened! I wish that I didn't have to depend on rand_core at all. I'll publish my changes tomorrow.

**Comment by ninjasource** [comment]
Ok, I've made the update. Let me know if this solves your problem and I'll close the issue. Thanks for raising the issue.

**Comment by jgarvin** [comment]
Awesome thanks 👍
